# Generated by Django 5.2.8 on 2025-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
    ]
